name = "bygg_web"
version = "0.0.1"
target = "javascript"

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
bygg_core = { path = "../core" }

[dev-dependencies]
lustre_dev_tools = ">= 2.3.0 and < 3.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
